dorsia/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import patterns, include, url

# Enable admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'dorsia.views.home', name='home'),
    url(r'^menu$', 'dorsia.views.menu', name='menu'),
    url(r'^reservations$', 'dorsia.views.reservations', name='reservations'),
    url(r'^reviews$', 'dorsia.views.reviews', name='reviews'),
)

dorsia/models.py
# -*- coding: utf-8 -*-


from datetime import datetime

from django.forms import ModelForm
from django.db import models


PARTY_SIZE_CHOICES = zip(range(1, 21), range(1, 21))
SEATING_TIME_CHOICES = ((6, 6), (8, 8))


class Reservation(models.Model):

    name = models.CharField(blank=False, max_length=100)
    email = models.EmailField(blank=False, max_length=254)
    partySize = models.IntegerField(blank=False, choices=PARTY_SIZE_CHOICES)
    reservationDate = models.DateField(blank=False)
    seatingTime = models.PositiveSmallIntegerField(blank=False, choices=SEATING_TIME_CHOICES)
    createdAt = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return '%s, party of %d, %s %d' % (self.name, self.partySize,
                                           datetime.strftime(self.reservationDate, '%Y-%m-%d'),
                                           self.seatingTime)


class ReservationForm(ModelForm):
    class Meta:
        model = Reservation

dorsia/views.py
# -*- coding: utf-8 -*-


from django.core.mail import EmailMultiAlternatives
from django.template import Context
from django.template import RequestContext
from django.template.loader import get_template
from django.shortcuts import render_to_response

from dorsia.models import ReservationForm


def home(request):
    return render_to_response('home.html', {'currentPage': 'home'},
                              context_instance=RequestContext(request))


def menu(request):
    return render_to_response('menu.html', {'currentPage': 'menu'},
                              context_instance=RequestContext(request))


def reservations(request):
    '''Reservations page'''
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save()

            # Send email confirmation
            subject = 'Dorsia reservation'
            from_email, to = 'reservation@dorsianyc.com', form.cleaned_data['email']
            txt = get_template('emails/reservation.txt')
            html = get_template('emails/reservation.html')
            data = Context({
                'name': form.cleaned_data['name'],
                'reservation_date': form.cleaned_data['reservationDate'],
                'seating_time': form.cleaned_data['seatingTime'],
                'party_size': form.cleaned_data['partySize'],
            })
            text_content = txt.render(data)
            html_content = html.render(data)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            # Make main content text/html and attach alternative text only version
            # msg.content_subtype = 'html'
            msg.attach_alternative(html_content, 'text/html')
            msg.send(fail_silently=False)

            form = None
    else:
        form = ReservationForm()

    data = {'currentPage': 'reservations', 'form': form}
    return render_to_response('reservations.html', data,
                              context_instance=RequestContext(request))


def reviews(request):
    return render_to_response('reviews.html', {'currentPage': 'reviews'},
                              context_instance=RequestContext(request))

dorsia/templates/home.html
{% extends "layouts/application.html" %}

{% block content %}
      <div class="hero-unit">
        <h1>Dorsia</h1>
        <p><a class="btn btn-large" href="/reservations">Make a reservation &raquo;</a></p>
        <img alt="Photograph Salt &amp; Pepper by Marco Hofmann on 500px"
        class="shadow" src="http://pcdn.500px.net/5866410/5432635d669d30ae6e7ea29a860e019b43979a18/4.jpg">
      </div>
{% endblock content %}

dorsia/templates/layouts/_footer.html
{% load staticfiles %}
<footer>
  <p><span>5 East 19th Street (btwn 5th &amp; Broadway), New York, NY 10003</span>
  &#124; <span>646.480.6046</span> &#124; <span>&copy; Dorsia {% now "Y" %}</span>
  </p>
</footer>

dorsia/templates/layouts/_header.html
{% load staticfiles %}
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Dorsia</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="{% if "menu" == currentPage %}active{% endif %}">
          <a href="{% url "menu" %}">Menu</a>
          </li>
          <li class="{% if "reservations" == currentPage %}active{% endif %}">
          <a href="{% url "reservations" %}">Reservations</a>
          </li>
          <li class="{% if "reviews" == currentPage %}active{% endif %}">
          <a href="{% url "reviews" %}">Reviews</a>
          </li>
        </ul>
      </div> <!-- /.nav-collapse -->
    </div>
  </div>
</div>

dorsia/templates/layouts/application.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Dorsia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static "css/bootstrap.css" %}" media="all" rel="stylesheet" type="text/css" />
    <link href="{% static "css/application.css" %}" media="all" rel="stylesheet" type="text/css" />
    <link href="{% static "css/bootstrap-responsive.css" %}" media="all" rel="stylesheet" type="text/css" />
    <link href="{% static "css/bootstrap-datepicker.css" %}" media="all" rel="stylesheet" type="text/css" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-39099728-1']);
      _gaq.push(['_setDomainName', 'dorsianyc.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>

  <body>
    {% include "layouts/_header.html" %}

    <div class="{% block containerClass %}container{% endblock containerClass %}">
      {% block content %}
      {% endblock content %}

      {% include "layouts/_footer.html" %}
    <div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/bootstrap-datepicker.js" %}" type="text/javascript"></script>
  </body>
</html>

dorsia/templates/menu.html
{% extends "layouts/application.html" %}

{% block containerClass %}container-fluid{% endblock containerClass %}

{% block content %}
    <div class="hero-unit menu">
      <h1>Menu</h1>
      <ul class="menu-list">
        <li class="nav-header"><p>Entr&eacute;es</p></li>
        <li class="active">Sea Urchin Ceviche</li>
        <li>Puget Sound Olympia Oysters</li>
        <li class="nav-header">Relev&eacute;s</li>
        <li>Garlic and Rosemary Lamb</li>
        <li>Saute of Chicken, Lyonnaise</li>
        <li class="nav-header">Main Courses</li>
        <li>Roast Duckling, Apple Sauce</li>
        <li>Sirloin of Beef, Chateau Potatoes</li>
        <li class="nav-header">Salads</li>
        <li>Roast Squab &amp; Cress</li>
        <li>Cold Asparagus Vinaigrette</li>
        <li class="nav-header">Desserts</li>
        <li>Peaches in Chartreuse Jelly</li>
        <li>Chocolate & Vanilla Éclairs</li>
      </ul>
    </div>
{% endblock content %}

dorsia/templates/reservations.html
{% extends "layouts/application.html" %}

{% comment %} Datepicker adapted from http://dl.dropbox.com/u/143355/datepicker/datepicker.html {% endcomment %}

{% block content %}
      {% if form %}
      <h1>Reservations</h1>
      <form action="{% url "reservations" %}" method="post" id="reservation-form">
        {% csrf_token %}

        <fieldset>
          <legend>Make a reservation</legend>
          {{ form.non_field_errors }}

          <div class="row">
            <label for="id_name">Full name:</label>
            <div class="input">
              {{ form.name }}
            </div>
            {{ form.name.errors }}
          </div>

          <div class="row">
            <label for="id_email">Email:</label>
            <div class="input">
              {{ form.email }}
            </div>
            {{ form.email.errors }}
          </div>

          <div class="row">
            <label for="id_partySize">Party size:</label>
            <div class="input">
              {{ form.partySize }}
            </div>
            {{ form.partySize.errors }}
          </div>

          <div class="row">
            <label for="reservationDate">Date:</label>
            <div class="input">
              <input id="reservationDate" name="reservationDate" data-datepicker="datepicker" class="small" type="text" value="{% now "Y-m-d" %}" />
              {{ form.seatingTime }} PM
            </div>
            {% if form.reservationDate.errors %}
              {{ form.reservationDate.errors }}
            {% else %}{% if form.seatingTime.errors %}
              {{ form.seatingTime.errors }}
            {% endif %}{% endif %}
          </div>

          <div class="actions">
            <input type="submit" class="btn btn-large" value="Submit" />
          </div>
        </fieldset>
      </form>

      {% else %}
      <p>Thanks for making a reservation. Confirm your reservation by checking the email we sent you.</p>
      {% endif %}

{% endblock content %}

dorsia/templates/reviews.html
{% extends "layouts/application.html" %}

{% block content %}
  <h1>Reviews</h1>

  <div class="row">
    <div class="span4">
      <p>Ivana Trump Eats Here I saw her once...sitting at a table next to two businessmen. I'm not sure why she was there. Or was it Texarkana. I get my restaurants mixed up.
      <p>&mdash; Patrick Bateman</p>
    </div>

    <div class="span4">
      <p>Dorisa on Friday night. How do you swing that?</p>
      <p>&mdash; Timothy Bryce</p>
    </div>

    <div class="span4">
      <p>Great sea urchin ceviche!</p>
      <p>&mdash; Paul Allen</p>
    </div>
  </div>

  <div class="row">
    <div class="span4">
      <a class="review-link" href="https://www.facebook.com/pages/Dorsia/55984183346" alt="Facebook page" title="Facebook page">Facebook page</a>
      <a class="review-link" href="http://www.yelp.com/biz/dorsia-new-york" alt="Yelp reviews" title="Yelp review">Yelp reviews</a>
    </div>
    <!-- <div class="span4"> -->
      <!-- <p><strong>Hey Paul!</strong> [he bashes Allen in the head with the axe, and blood splatters over him] -->
      <!-- <strong>Try getting a reservation at Dorsia now you fucking stupid bastard! You fucking bastard!</strong> -->
      <!-- </p> -->
      <!-- <p>&mdash; Patrick Bateman</p> -->
    <!-- </div> -->

    <!-- <div class="span4"> -->
      <!-- <p>I could&rsquo;ve gotten us a table. Nobody goes there anymore.</p> -->
      <!-- <p>&mdash; Marcus Halberstram</p> -->
    <!-- </div> -->

    <!-- <div class="span4"> -->
      <!-- <p>God, I hate this place. It&rsquo;s a chick restaurant. Why aren't we at Dorsia?</p> -->
      <!-- <p>&mdash; Timothy Bryce</p> -->
    <!-- </div> -->
  </div>
{% endblock content %}